version: '3.1'

services:

  mysql:
    volumes:
      - mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./mysql-files:/var/lib/mysql-files
    container_name: mysql
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prova 
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

volumes:
  mysql:
